apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  selector:
    matchLabels:
      app: flask-test-app
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
        - name: flask-test-app
          image: flask-test-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000