version: "3"
services:

  transaction-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:mysql://localhost:3306/main
      DB_USERNAME: admin
      DB_PASSWORD: password
      TOPIC: transactions
      BROKER_URL: localhost:9092
      EXCHANGE_RATE_API_KEY: f5e3b2652bd77b7bfb957642
    depends_on:
      - mariadb
      - kafka

  mariadb:
    image: "mariadb:10.5"
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql/data:/temp/data
      - /var/lib/mysql/logs:/temp/logs
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_NETWORK_THREADS: 4
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 1048576
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 536870912
      KAFKA_JMX_PORT: 7071
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    links:
      - zookeeper

  zookeeper:
    image: digitalwonderland/zookeeper
    environment:
      - ZOOKEEPER_ID="1"
      - ZOOKEEPER_SERVER_1=localhost
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888